EXPERIMENT:
  NAME: ""
  TAG: "sdd_dkd_lskd,res32x4,shuv1"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SDD_DKD_LSKD"
  TEACHER: "resnet32x4_sdd"
  STUDENT: "ShuffleV1_sdd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  CE_WEIGHT: 1.0
  ALPHA: 9.0
  BETA: 72.0
  T: 2.0
  WARMUP: 20
DATASET:
  TYPE: "cifar100"
  NUM_WORKERS: 8
