EXPERIMENT:
  NAME: ""
  TAG: "sdd_kd_lskd,wrn40_2,mv2,cub200"
  PROJECT: "cub200_baselines"
DISTILLER:
  TYPE: "SDD_KD_LSKD"
  TEACHER: "wrn_40_2_sdd"
  STUDENT: "MobileNetV2_sdd"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
KD:
  TEMPERATURE: 2.0
  LOSS:
    CE_WEIGHT: 1.0
    KD_WEIGHT: 9.0
DATASET:
  TYPE: "cub200"
  NUM_WORKERS: 32
