EXPERIMENT:
  NAME: ""
  TAG: "sdd_lskd_cpu_test,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SDD_LSKD"
  TEACHER: "resnet32x4_sdd"
  STUDENT: "resnet8x4_sdd"
SOLVER:
  BATCH_SIZE: 32  # Smaller batch for CPU
  EPOCHS: 2  # Very quick CPU test
  LR: 0.05
  LR_DECAY_STAGES: [1]  # Adjusted for 2 epochs
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 8.0
  T: 4.0
  WARMUP: 1  # Adjusted for 2 epochs
DATASET:
  TYPE: "cifar100"
  NUM_WORKERS: 1  # Minimal workers for CPU
