EXPERIMENT:
  NAME: ""
  TAG: "sdd_lskd,vgg13,mv2"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "SDD_LSKD"
  TEACHER: "vgg13"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  CE_WEIGHT: 1.0
  ALPHA: 1.0
  BETA: 8.0
  T: 4.0
  WARMUP: 20
DATASET:
  TYPE: "cifar100"
  NUM_WORKERS: 2
